name: Install Dependencies

runs:
  using: composite
  steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "Install Linux dependencies"
        sudo apt-get update
	sudo apt-get install -y cmake
        sudo apt-get install -y libgmp-dev
        sudo apt-get install -y python3-pip
	pip3 install sympy
        echo "Install Linux dependencies [DONE]"